version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '12:00'
    timezone: Australia/ACT
  open-pull-requests-limit: 10
  assignees:
  - jonchang
