language: ruby
dist: trusty
rvm:
    - 2.5.1

services:
    - docker

cache:
    bundler: true
    directories:
        - .asset-cache/
        - .jekyll-cache/

env:
    global:
        - JEKYLL_ENV=production

before_install:
    - scripts/docker.sh

script:
    - rake
    - scripts/test.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
