language: ruby
dist: trusty
rvm:
    - 2.4.1

cache:
    bundler: true
    directories:
        - $HOME/R/Library
        - .asset-cache/
        - .jekyll-cache/

env:
    global:
        - R_LIBS_USER=$HOME/R/Library
        - JEKYLL_ENV=production

addons:
    apt:
        sources:
            - r-packages-trusty
        packages:
            - r-base-dev

before_install:
    - Rscript -e 'install.packages(c("ape", "tidyverse", "glue", "future"), repos = "https://cran.rstudio.com", Ncpu = parallel::detectCores())'

script:
    - scripts/generate_fossils.R
    - scripts/generate_taxonomy.R
    - bundle exec jekyll build --baseurl /fishtreeoflife.org

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
