language: ruby
dist: trusty
rvm:
    - 2.5.1

services:
    - docker

cache:
    bundler: true
    directories:
        - .asset-cache/
        - .jekyll-cache/

env:
    global:
        - JEKYLL_ENV=production

before_install:
    - docker pull jonchang/fishtreeoflife-docker
    - docker run --name temp jonchang/fishtreeoflife-docker /bin/true
    - docker cp temp:_assets _assets_tmp
    - docker cp temp:_fossils _fossils
    - docker cp temp:_data _data_tmp
    - docker rm temp
    - cp -R _assets_tmp/* _assets
    - cp -R _data_tmp/* _data
    - rm -rf _assets_tmp _data_tmp


deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
