language: ruby
dist: trusty
rvm:
    - 2.4.1

cache:
    bundler: true
    directories:
        - $HOME/R/Library

env:
    - R_LIBS_USER=$HOME/R/Library
    - JEKYLL_ENV=production

addons:
    apt:
        sources:
            - r-packages-trusty
        packages:
            - r-base-dev

before_install:
    - Rscript -e 'install.packages(c("ape", "tidyverse", "glue"), repos = "https://cran.rstudio.com", Ncpu = 2)'

script:
    #- ts/generate_taxonomy.R
    - bundle exec jekyll build --baseurl /fishtreeoflife.org
    - touch _site/.nojekyll

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
