language: ruby
dist: bionic
rvm:
    - 2.6.3

services:
    - docker

cache:
    bundler: true

env:
    global:
        - JEKYLL_ENV=production

before_install:
    - gem update --system
    - gem install bundler
    - scripts/docker.sh

script:
    - rake
    - scripts/test.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
