language: ruby
dist: trusty
rvm:
    - 2.4.1

cache:
    bundler: true

addons:
    apt:
        packages:
            - r-base

script:
    #- ts/generate_taxonomy.R
    - bundle exec jekyll build
    - touch _site/.nojekyll

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
