language: ruby
dist: trusty
rvm:
    - 2.6.0

services:
    - docker

cache:
    bundler: true

env:
    global:
        - JEKYLL_ENV=production
        - RUBYOPT="--jit"

before_install:
    - scripts/docker.sh

script:
    - rake
    - scripts/test.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master
