name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  build:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Github Docker
      run: |
        echo -n $GITHUB_TOKEN | docker login -u jonchang --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download data from the fishtreeoflife docker container
      run: scripts/docker.sh
      
    - run: sudo apt update && sudo apt install -y libyaml-dev

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - id: pages
      uses: actions/configure-pages@v4

    - name: Build site
      run: rake
      env:
          JEKYLL_ENV: production

    - name: Test site
      run: scripts/test.sh

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    concurrency:
      group: "pages"
      cancel-in-progress: true
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - id: deployment
      uses: actions/deploy-pages@v2
