name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Login to Github Docker
      run: |
        echo -n $GITHUB_TOKEN | docker login -u jonchang --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download data from the fishtreeoflife docker container
      run: scripts/docker.sh

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Build site
      run: rake
      env:
          JEKYLL_ENV: production

    - name: Test site
      run: scripts/test.sh

    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      with:
        publish_dir: ./_site
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
