name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install libvips
      run: |
        sudo apt update
        sudo apt install --no-install-recommends -y libvips
    - uses: actions/checkout@v2
    - name: Login to Github Docker
      run: |
        # Conditionally use secret token with permissions if available
        export TOKEN="${PACKAGE_ACCESS_TOKEN:-$GITHUB_TOKEN}"
        echo -n $TOKEN | docker login -u jonchang --password-stdin docker.pkg.github.com
      env:
        PACKAGE_ACCESS_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download data from the fishtreeoflife docker container
      run: scripts/docker.sh
    - name: Build fishtree R package documentation
      run: scripts/fishtree_docs.sh
    - uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: '2.x'
    - name: Update bundled packages
      run: gem install bundler && bundle update --bundler && bundle install
    - name: Build site
      run: rake
      env:
          JEKYLL_ENV: production
    - name: Test site
      run: scripts/test.sh
    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      with:
        publish_dir: ./_site
        personal_token: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      run: shellcheck ./scripts/*
